Repository antonbabenko/pre-commit-terraform, pull requests merged in 2021-10, with the labels that each got.

#211 fix: terraform_tflint hook executes in a serial way to run less often
  .pre-commit-hooks.yaml
Labels: bug, hook/terraform_tflint, estimate/1h

#235 docs: Add contributing guide and docs about performance tests
  .editorconfig
  .github/CONTRIBUTING.md
  .gitignore
  README.md
  tests/Dockerfile
  tests/hooks_performance_test.sh
Labels: feature, documentation, estimate/1h

#238 docs: Document terraform_tfsec args usage
  README.md
Labels: documentation, estimate/1h, hook/terraform_tfsec

#173 feat: Add new hook for `terraform providers lock` operation
  .pre-commit-hooks.yaml
  CHANGELOG.md
  README.md
  terraform_providers_lock.sh
Labels: feature, estimate/1day
